name: Pull Request Workflow

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.26.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          lfs: true
          submodules: recursive

      - name: Verify Go code
        uses: ./.github/actions/go-verify
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - name: Install Python test dependencies
        run: python -m pip install -r requirements.txt

      - name: Build mocks
        run: make mocks

      - name: Run mock integration tests
        run: make test-with-mocks

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: |
            tests/results/log.html
            tests/results/sut.log
